-- Query for RC009
use PPIVSahayogiVBL

Declare @MigDate date, @v_MigDate nvarchar(15)
set @MigDate =(select Today from ControlTable);
set @v_MigDate=REPLACE(REPLACE(CONVERT(VARCHAR,@MigDate,106), ' ','-'), ',','')

IF OBJECT_ID('tempdb.dbo.#FinalMaster', 'U') IS NOT NULL
  DROP TABLE #FinalMaster;

select * INTO #FinalMaster from (
SELECT  DISTINCT
        G.cif_id,
		t.ClientCode
		,AcType
		,t.Name
		,t.PinnedMesg
		,BranchCode
		,M.Obligor
		,min(AcOpenDate) AS AcOpenDate
		,MainCode
    	,CyDesc as CyCode
		,IsBlocked
		,Key_Risk_Grade
		,M.AcOfficer
,ROW_NUMBER() OVER( PARTITION BY t.ClientCode ORDER BY AcOpenDate) AS SerialNumber
FROM Master M  join ClientTable t 
on M.ClientCode=t.ClientCode
join FINMIG..GEN_CIFID G
on G.ClientCode = t.ClientCode
join CurrencyTable C
on M.CyCode = C.CyCode
WHERE G.ClientSeg = 'R'

GROUP BY t.ClientCode, AcType,G.cif_id, BranchCode, Key_Risk_Grade,t.Name,t.PinnedMesg, M.Obligor, AcOpenDate, MainCode, IsBlocked, M.AcOfficer,M.CyCode,C.CyDesc

)x
where SerialNumber=1;

SELECT DISTINCT
t1.cif_id AS ORGKEY
,'' AS COMMUNICATION_LANGUAGE
,'' AS PREFERRED_ADDRESS_MODE
,'' AS BEHAVIOURAL_SCORE
,CASE WHEN ltrim(upper(Key_Risk_Grade)) like 'H%' THEN 'HIG'
WHEN ltrim(upper(Key_Risk_Grade)) like 'M%' THEN 'MIG'
WHEN ltrim(upper(Key_Risk_Grade)) like 'L%' THEN 'LOW'
ELSE 'MIG' END AS RISK_BEHAVIOUR
,'' AS OTHER_BEHAVIOURAL_PROFILE
,'' AS LIFE_CYCLE_STAGE
,'' AS SERVICE_PERSONALISE
,'' AS PSYCHOGRAPHICTYPE
,'' AS PRIORITY_IDENTIFIER
,'' AS HOUSEHOLD_NUMBER
,'' AS PREFERRED_REP
,'' AS SEGMENTATION_CLASS
,isnull(replace(SUBSTRING(t1.Name,1,charindex(' ',t1.Name)),' ' , ''),'.') AS PREFERREDNAME 
,'' AS NUMBEROFDEPENDANTS
,'' AS NUMBEROFDEPENDANTCHILDREN
,'' AS STMTDATEFORCOMBSTMT
,'' AS SUBSEGMENT
,'' AS HOBBYFIELD1
,'' AS HOBBYFIELD2
,'' AS HOBBYFIELD3
,'' AS HOBBYFIELD4
,'' AS HOBBYFIELD5
,'' AS HOBBYFIELD6
,'' AS PROFILE_FIELD1
,'' AS PROFILE_FIELD2
,'' AS PROFILE_FIELD3
,'' AS PROFILE_FIELD4
,'' AS ALERT1
,'' AS ALERT2
,'' AS ALERT3
,'' AS ALERT4
,'' AS ALERT5
,'' AS FLAG1
,'' AS FLAG2
,'' AS FLAG3
,'' AS FLAG4
,'' AS FLAG5
,'' AS BANK_DEFINED_PREFER_VAR1
,'' AS BANK_DEFINED_PREFER_VAR2
,'' AS BANK_DEFINED_PREFER_VAR3
,'' AS BANK_DEFINED_PREFER_DATE1
,'' AS BANK_DEFINED_PREFER_DATE2
,'' AS BANK_DEFINED_PREFER_DATE3
,'' AS USERFIELD1
,'' AS USERFIELD2
,'' AS USERFIELD3
,'' AS USERFIELD4
,'' AS USERFIELD5
,'' AS USERFIELD6
,'' AS SPSERVICEREQUIRED1
,'' AS SPSERVICEREQUIRED2
,'' AS SPSERVICEREQUIRED3
,'' AS SPSERVICEREQUIRED4
,'' AS SPSERVICEREQUIRED5
,'' AS USERFLAG1
,'' AS USERFLAG2
,'' AS PREFRELSHIPDISCOUNT1
,'' AS PREFRELSHIPDISCOUNT2
,'' AS PREFRELSHIPDISCOUNTPERCENT1
,'' AS PREFRELSHIPDISCOUNTPERCENT2
,'' AS USERFIELD7
,'' AS USERFIELD8
,'' AS USERFIELD9
,'' AS USERFIELD10
,'' AS USERFIELD11
,'' AS USERFIELD12
,'' AS USERFIELD13
,'' AS AMOUNT1
,'' AS AMOUNT2
,'' AS AMOUNT3
,'' AS AMOUNT4
,'' AS AMOUNT5
,'' AS AMOUNT6
,'' AS AMOUNT7
,'' AS INTFIELD1
,'' AS INTFIELD2
,'' AS INTFIELD3
,'' AS INTFIELD4
,'' AS INTFIELD5
,'' AS STATEMENTTYPE
,'DEMND' AS STATEMENTFREQUENCY
,'' AS STMTDATEWEEKDAY
,'' AS STMTMONTHLYSTARTDATE
,'' AS ACTIONDURINGHOLIDAY
,'' AS DESPATCHMODE
,'' AS CALENDERTYPE
,'' AS DISCOUNTAVAILED
,'' AS DISCOUNTTYPE
,'' AS PREFEFFECTIVEDATE
,'' AS PREFEXPIRYDATE
,'' AS LASTCONTACTEDDATE
,'' AS LASTCONTACTEDCHANNEL
,'' AS FAMILYTYPE
,'' AS NOOFEARNERS
--,left(isnull(t2.PinnedMesg,''),50) as REMARKS
,left(REPLACE(REPLACE(t1.PinnedMesg, CHAR(13), ''), CHAR(10), ''),50) as REMARKS
,'' AS COMMUNITY
,'' AS LTVINDICATOR
,'' AS ASSETCLASSIFICATION
,'' AS ASSETCLASSIFICATIONDESC
,'' AS ASSETCLASSIFIEDON
,'' AS CUSTHEALTHCODE
,'' AS CREDITDISCOUNTPERCENT
,'' AS DEBITDISCOUNTPERCENT
,'' AS PREFERRENTIALEXPIRYDATE
,'' AS INTERESTDESCRIPTION
,'' AS STMTWEEKOFMONTH
,'' AS CUSTCHARGECODE
,'' AS CUSTCHARGE
,'' AS CHARGEDEBITFORACID
,'' AS CHARGEDEBITSOLID
,'' AS CHARGEHISTORYFLAG
,t1.CyCode AS CUSTOMERCURRENCY
--,CyDesc as CUSTOMERCURRENCY
,'' AS LOANSSTATEMENTTYPE
,'' AS TDSSTATEMENTTYPE
,'' AS COMBSTMTCHARGECODE
,'' AS TDSCUSTFLOORLIMIT
,'' AS COMMUNITY_CODE
,'' AS CUST_HEALTH_REF_CODE
,'' AS CUST_PREF_TILL_DATE
,'' AS CU_TDSCUSTFLOORLIMIT
,'' AS [CHECKSUM]
,'en_US' AS PREFERRED_LOCALE
,'01' AS BANK_ID
,'' AS EXT_SYS_PRICING
,'' AS PRICING_EFFECTIVE_DATE
,'' AS PRICING_REVIEW_DATE
,'' AS RELATIONSHIP_PRICING_ID
FROM #FinalMaster t1
order by ORGKEY
