use PPIVSahayogiVBL;
-- Query for RC003

SELECT DISTINCT
t2.ClientCode
,G.cif_id AS ORGKEY
,G.cif_id AS CIFID
,'' AS STRTEXT2 --changed in sahayogi migration
,'' AS STRTEXT1
,'CURRENCY' AS TYPE
,ISNULL(CyDesc,'NPR') as CUSTOMERCURRENCY
--,t1.CyCode AS CUSTOMERCURRENCY
,'' AS CREDITDISCOUNTPERCENT
,'' AS DEBITDISCOUNTPERCENT
,'' AS WITHHOLDTAXPCNT
,'' AS WITHHOLDTAXFLOORLMT
,'30-Dec-2099' AS DTDATE1
,'' AS DTDATE2
,'NP' AS COUNTRYOFISSUE_CODE
,'' AS SMALL_STR1
,'' AS SMALL_STR2
,'' AS SMALL_STR3
,'' AS SMALL_STR4
,'' AS SMALL_STR5
,'' AS SMALL_STR6
,'' AS SMALL_STR7
,'' AS SMALL_STR8
,'' AS SMALL_STR9
,'' AS SMALL_STR10
,'' AS MED_STR1
,'' AS MED_STR2
,'' AS MED_STR3
,'' AS MED_STR4
,'' AS MED_STR5
,'' AS MED_STR6
,'' AS MED_STR7
,'' AS MED_STR8
,'' AS MED_STR9
,'' AS MED_STR10
,'' AS LARGE_STR1
,'' AS LARGE_STR2
,'' AS LARGE_STR3
,'' AS LARGE_STR4
,'' AS LARGE_STR5
,'' AS DATE1
,'' AS DATE2
,'' AS DATE3
,'' AS DATE4
,'' AS DATE5
,'' AS DATE6
,'' AS DATE7
,'' AS DATE8
,'' AS DATE9
,'' AS DATE10
,'' AS NUMBER1
,'' AS NUMBER2
,'' AS NUMBER3
,'' AS NUMBER4
,'' AS NUMBER5
,'' AS NUMBER6
,'' AS NUMBER7
,'' AS NUMBER8
,'' AS NUMBER9
,'' AS NUMBER10
,'' AS DECIMAL1
,'' AS DECIMAL2
,'' AS DECIMAL3
,'' AS DECIMAL4
,'' AS DECIMAL5
,'' AS DECIMAL6
,'' AS DECIMAL7
,'' AS DECIMAL8
,'' AS DECIMAL9
,'' AS DECIMAL10
,'' AS STRTEXT3
,'' AS STRTEXT4
,'' AS STRTEXT5
,'' AS STRTEXT6
,'' AS STRTEXT7
,'' AS STRTEXT8
,'' AS STRTEXT9
--, CASE WHEN t1.CyCode = t1.CyCode THEN t1.CyCode ELSE '01' END AS STRTEXT10
,ISNULL(CyDesc,'NPR') AS STRTEXT10
,'' AS INTINTEGER1
,'' AS INTINTEGER2
,'' AS INTINTEGER3
,'' AS INTINTEGER4
,'' AS INTINTEGER5
,'' AS INTINTEGER6
,'' AS INTINTEGER7
,'' AS INTINTEGER8
,'' AS INTINTEGER9
,'' AS INTINTEGER10
,'' AS INTINTEGER11
,'' AS INTINTEGER12
,'' AS INTINTEGER13
,'' AS INTINTEGER14
,'' AS INTINTEGER15
,'' AS DTDATE3
,'' AS DTDATE4
,'' AS DTDATE5
,0 AS DBFLOAT1
,0 AS DBFLOAT2
,0 AS DBFLOAT3
,0 AS DBFLOAT4
,'' AS DBFLOAT5
,'' AS STRTEXT11
,'' AS STRTEXT12
,'' AS STRTEXT13
,'' AS STRTEXT14
,'' AS STRTEXT15
,'' AS STRTEXT16
,'' AS STRTEXT17
,'' AS STRTEXT18
,'' AS STRTEXT19
,'' AS STRTEXT20
,'' AS STRTEXT21
,'DEF_VALUE' AS STRTEXT22
,'' AS STRTEXT23
,'' AS STRTEXT24
,'' AS STRTEXT25
,'' AS STRTEXT26
,'' AS STRTEXT27
,'' AS EMPLOYERID
,'' AS EMPLOYEEID
,'' AS STRTEXT1_CODE
,'' AS STRTEXT2_CODE
,'' AS STRTEXT28
,'01' AS BANK_ID
FROM Master t1 JOIN ClientTable t2 ON t1.ClientCode = t2.ClientCode
join FINMIG..GEN_CIFID G on G.ClientCode = t1.ClientCode
join CurrencyTable C
on t1.CyCode = C.CyCode
WHERE G.ClientSeg = 'R'


union all

select * from (
SELECT DISTINCT
t2.ClientCode
,G.cif_id AS ORGKEY
,G.cif_id AS CIFID

,case 
	when rtrim(ltrim(OccupationList)) = 'AGRICULTURE' then 'AGP'
	when rtrim(ltrim(OccupationList)) = 'BUSINESS' then 'BSM'
	when rtrim(ltrim(OccupationList)) = 'DOCTOR' then 'DR'
	when rtrim(ltrim(OccupationList)) = 'ENGINEER' then 'ENG'
	when rtrim(ltrim(OccupationList)) = 'HOME MAKER' then 'HOW'
	when rtrim(ltrim(OccupationList)) = 'HOUSEWIFE' then 'HOW'
	when rtrim(ltrim(OccupationList)) = 'NEPAL ARMY' then 'ARM'
	when rtrim(ltrim(OccupationList)) = 'NEPAL POLICE' then 'POL'
	when rtrim(ltrim(OccupationList)) like 'OTHER%' then 'OTH'
	when rtrim(ltrim(OccupationList)) = 'PLEASE SPECIFY' then 'OTH'
	when rtrim(ltrim(OccupationList)) = 'PROFESSOR' then 'PROF'
	when rtrim(ltrim(OccupationList)) = 'RETIRED' then 'RET'
	when rtrim(ltrim(OccupationList)) = 'SALARY PERSON' then 'EMP'
	when rtrim(ltrim(OccupationList)) = 'SELF EMPLOYED' then 'SEM'
	when rtrim(ltrim(OccupationList)) = 'SERVICE' then 'SERV'
	when rtrim(ltrim(OccupationList)) = 'STUDENT' then 'STD'
	else '' END AS STRTEXT2 --changed in sahayogi migration
 
,'' AS STRTEXT1
,'CURRENT_EMPLOYMENT' AS TYPE
,ISNULL(CyDesc,'NPR') as CUSTOMERCURRENCY
--,t1.CyCode AS CUSTOMERCURRENCY
,'' AS CREDITDISCOUNTPERCENT
,'' AS DEBITDISCOUNTPERCENT
,'' AS WITHHOLDTAXPCNT
,'' AS WITHHOLDTAXFLOORLMT
,'30-Dec-2099' AS DTDATE1
,'' AS DTDATE2
,'NP' AS COUNTRYOFISSUE_CODE
,'' AS SMALL_STR1
,'' AS SMALL_STR2
,'' AS SMALL_STR3
,'' AS SMALL_STR4
,'' AS SMALL_STR5
,'' AS SMALL_STR6
,'' AS SMALL_STR7
,'' AS SMALL_STR8
,'' AS SMALL_STR9
,'' AS SMALL_STR10
,'' AS MED_STR1
,'' AS MED_STR2
,'' AS MED_STR3
,'' AS MED_STR4
,'' AS MED_STR5
,'' AS MED_STR6
,'' AS MED_STR7
,'' AS MED_STR8
,'' AS MED_STR9
,'' AS MED_STR10
,'' AS LARGE_STR1
,'' AS LARGE_STR2
,'' AS LARGE_STR3
,'' AS LARGE_STR4
,'' AS LARGE_STR5
,'' AS DATE1
,'' AS DATE2
,'' AS DATE3
,'' AS DATE4
,'' AS DATE5
,'' AS DATE6
,'' AS DATE7
,'' AS DATE8
,'' AS DATE9
,'' AS DATE10
,'' AS NUMBER1
,'' AS NUMBER2
,'' AS NUMBER3
,'' AS NUMBER4
,'' AS NUMBER5
,'' AS NUMBER6
,'' AS NUMBER7
,'' AS NUMBER8
,'' AS NUMBER9
,'' AS NUMBER10
,'' AS DECIMAL1
,'' AS DECIMAL2
,'' AS DECIMAL3
,'' AS DECIMAL4
,'' AS DECIMAL5
,'' AS DECIMAL6
,'' AS DECIMAL7
,'' AS DECIMAL8
,'' AS DECIMAL9
,'' AS DECIMAL10
,'' AS STRTEXT3
,'' AS STRTEXT4
,'' AS STRTEXT5
,'' AS STRTEXT6
,'' AS STRTEXT7
,'' AS STRTEXT8
,'' AS STRTEXT9
--, CASE WHEN t1.CyCode = t1.CyCode THEN t1.CyCode ELSE '01' END AS STRTEXT10
,'' AS STRTEXT10
,'' AS INTINTEGER1
,'' AS INTINTEGER2
,'' AS INTINTEGER3
,'' AS INTINTEGER4
,'' AS INTINTEGER5
,'' AS INTINTEGER6
,'' AS INTINTEGER7
,'' AS INTINTEGER8
,'' AS INTINTEGER9
,'' AS INTINTEGER10
,'' AS INTINTEGER11
,'' AS INTINTEGER12
,'' AS INTINTEGER13
,'' AS INTINTEGER14
,'' AS INTINTEGER15
,'' AS DTDATE3
,'' AS DTDATE4
,'' AS DTDATE5
,0 AS DBFLOAT1
,0 AS DBFLOAT2
,0 AS DBFLOAT3
,0 AS DBFLOAT4
,'' AS DBFLOAT5
,'' AS STRTEXT11
,'' AS STRTEXT12
,'' AS STRTEXT13
,'' AS STRTEXT14
,'' AS STRTEXT15
,'' AS STRTEXT16
,'' AS STRTEXT17
,'' AS STRTEXT18
,'' AS STRTEXT19
,'' AS STRTEXT20
,'' AS STRTEXT21
,'' AS STRTEXT22
,'' AS STRTEXT23
,'' AS STRTEXT24
,'' AS STRTEXT25
,'' AS STRTEXT26
,'' AS STRTEXT27
,'' AS EMPLOYERID
,'' AS EMPLOYEEID
,'' AS STRTEXT1_CODE
,'' AS STRTEXT2_CODE
,'' AS STRTEXT28
,'01' AS BANK_ID
FROM Master t1 JOIN ClientTable t2 ON t1.ClientCode = t2.ClientCode
join FINMIG..GEN_CIFID G on G.ClientCode = t1.ClientCode
join CurrencyTable C
on t1.CyCode = C.CyCode
WHERE G.ClientSeg = 'R' and isnull(OccupationList, '') <> '')b where STRTEXT2 <> ''

ORDER BY ORGKEY
--347513 rows in second migration 