use PPIVSahayogiVBL
-- Query for RC008

SELECT DISTINCT
G.cif_id AS ORGKEY
,CASE WHEN MaritalStatus='N' THEN 'SNGLE' 
 WHEN MaritalStatus='S' THEN 'SNGLE' 
 WHEN MaritalStatus='D' THEN 'DVORC'  
 WHEN MaritalStatus='W' THEN 'WIDOW' 
 WHEN MaritalStatus='M' THEN 'MARRD' 
 ELSE 'MIG' END AS MARITAL_STATUS_CODE
,'OTH' EMPLOYMENT_STATUS
,'000' AS ANNUAL_SALARY_INCOME
,'' AS TDSEXCEMPTENDDATE
,'' AS TDSEXCEMPTSUBMITDATE
,'' AS TDSEXCEMPTREFNUM
,'' AS TDSEXCEMPTREMARKS
,'' AS CUSTCASTE
,'' AS CUSTBUSINESSASSETS
,'' AS CUSTPROPERTYASSETS
,'' AS CUSTINVESTMENTS
,'' AS CUSTNETWORTH
,'' AS CUSTDEPOSITSINOTHERBANKS
,'' AS ADVANCEASONDATE
,'' AS TOTALFUNDBASE
,'' AS TOTALNONFUNDBASE
,'' AS CUSTFINYEARENDMONTH
--,Cntry.CountryCode AS NATIONALITY_CODE
/*,CASE WHEN t2.CountryCode = '01' THEN '119' -- 'NEPALESE'
WHEN t2.CountryCode = '11' THEN '079' --'INDIAN'
WHEN t2.CountryCode = '21' THEN '004' --'AMERICAN'
WHEN t2.CountryCode = '23' THEN '011' --'AUSTRALIAN'
WHEN t2.CountryCode = '24' THEN '033' -- 'CANADIAN'
WHEN t2.CountryCode = '25' THEN '158' -- 'SWISS'
WHEN t2.CountryCode = '26' THEN  '064'--'GERMAN'
WHEN t2.CountryCode = '27' THEN '048'--'DUTCH'
WHEN t2.CountryCode = '32' THEN '012'--'AUSTRIAN'
ELSE '119'--'OTHERS'
END AS NATIONALITY_CODE
*/

,CASE WHEN t2.CountryCode = '01' THEN 'NP' -- 'NEPALESE'
WHEN t2.CountryCode = '11' THEN 'IN' --'INDIAN'
WHEN t2.CountryCode = '21' THEN 'AS' --'AMERICAN'
WHEN t2.CountryCode = '23' THEN 'AU' --'AUSTRALIAN'
WHEN t2.CountryCode = '24' THEN 'CA' -- 'CANADIAN'
WHEN t2.CountryCode = '25' THEN 'CH' -- 'SWISS'
WHEN t2.CountryCode = '26' THEN  'DE'--'GERMAN'
WHEN t2.CountryCode = '27' THEN 'NL'--'DUTCH'
WHEN t2.CountryCode = '32' THEN 'AT'--'AUSTRIAN'
ELSE 'NP'--'OTHERS'
END AS NATIONALITY_CODE

--,'01' AS RESIDENCECOUNTRY_CODE
,CASE when exists (select distinct C.ClientCode
from ClientTable C(NOLOCK), Master  M(NOLOCK), AcCustType A(NOLOCK) 
where C.ClientCode=M.ClientCode and M.BranchCode=A.BranchCode and M.MainCode=A.MainCode and A.CustTypeCode='B' 
and A.MainCode in (select MainCode from AcCustType(NoLock) where CustTypeCode='B')
and C.ClientCode=M.ClientCode 
--and C.ClientCategory like 'I%'
and A.CustType in ('CB','NB','XB','UB','DB','OB','WC') 
and C.ClientCode=t2.ClientCode) then (
	CASE WHEN t2.CountryCode = '11' THEN 'IN' --'INDIAN'
	WHEN t2.CountryCode = '21' THEN 'AS' --'AMERICAN'
	WHEN t2.CountryCode = '23' THEN 'AU' --'AUSTRALIAN'
	WHEN t2.CountryCode = '24' THEN 'CA' -- 'CANADIAN'
	WHEN t2.CountryCode = '25' THEN 'CH' -- 'SWISS'
	WHEN t2.CountryCode = '26' THEN  'DE'--'GERMAN'
	WHEN t2.CountryCode = '27' THEN 'NL'--'DUTCH'
	WHEN t2.CountryCode = '32' THEN 'AT'--'AUSTRIAN'
	ELSE 'AS'END) 
else 'NP' end as RESIDENCECOUNTRY_CODE

,'' AS NRERELATIVENAME
--,'E' AS NRECOUNTRYTYPE
,CASE when exists (select distinct C.ClientCode
from ClientTable C(NOLOCK), Master  M(NOLOCK), AcCustType A(NOLOCK) 
where C.ClientCode=M.ClientCode and M.BranchCode=A.BranchCode and M.MainCode=A.MainCode and A.CustTypeCode='B' 
and A.MainCode in (select MainCode from AcCustType(NoLock) where CustTypeCode='B')
and C.ClientCode=M.ClientCode 
--and C.ClientCategory like 'I%'
and A.CustType in ('CB','NB','XB','UB','DB','OB','WC') 
and C.ClientCode=t2.ClientCode) then 'E' else 'B' end as NRECOUNTRYTYPE

,'' AS DEMOGRAPHICTYPE
,'' AS PHONE_HOME
,'' AS PHONE_WORK
,'' AS EXTENSION
--,CASE WHEN t2.MobileNo = t2.MobileNo THEN t2.MobileNo ELSE '' END AS PHONE_CELL
,ISNULL(t2.MobileNo,'') AS PHONE_CELL
,'' AS FAX_WORK
--,CASE WHEN t2.eMail = t2.eMail THEN t2.eMail ELSE '' END AS EMAIL_HOME
--,ISNULL(t2.eMail,'') AS EMAIL_HOME
,case when FINMIG.dbo.F_IsValidEmail( t2.eMail)=1 then t2.eMail
		else '' end as EMAIL_HOME
,'' AS EMAIL_WORK
,'' AS EMAIL_PALM
,'' AS URL
,'' AS CUSTOMER_SEGMENT
,'' AS CUSTOMER_TYPE
/*,case when t1.CyCode is not null and t1.CyCode<>'' then t1.CyCode
else '999' end AS NATIONALITY
*/
,CASE WHEN t2.CountryCode = '01' THEN 'NP' -- 'NEPALESE'
WHEN t2.CountryCode = '11' THEN 'IN' --'INDIAN'
WHEN t2.CountryCode = '21' THEN 'AS' --'AMERICAN'
WHEN t2.CountryCode = '23' THEN 'AU' --'AUSTRALIAN'
WHEN t2.CountryCode = '24' THEN 'CA' -- 'CANADIAN'
WHEN t2.CountryCode = '25' THEN 'CH' -- 'SWISS'
WHEN t2.CountryCode = '26' THEN  'DE'--'GERMAN'
WHEN t2.CountryCode = '27' THEN 'NL'--'DUTCH'
WHEN t2.CountryCode = '32' THEN 'AT'--'AUSTRIAN'
ELSE 'NP'--'OTHERS'
END AS NATIONALITY
--,'Nepal' AS RESIDENCE_COUNTRY
,CASE when exists (select distinct C.ClientCode
from ClientTable C(NOLOCK), Master  M(NOLOCK), AcCustType A(NOLOCK) 
where C.ClientCode=M.ClientCode and M.BranchCode=A.BranchCode and M.MainCode=A.MainCode and A.CustTypeCode='B' 
and A.MainCode in (select MainCode from AcCustType(NoLock) where CustTypeCode='B')
and C.ClientCode=M.ClientCode 
--and C.ClientCategory like 'I%'
and A.CustType in ('CB','NB','XB','UB','DB','OB','WC') 
and C.ClientCode=t2.ClientCode) then (
	CASE WHEN t2.CountryCode = '11' THEN 'INDIA' --'INDIAN'
	WHEN t2.CountryCode = '21' THEN 'AMERICAN SAMOA' --'AMERICAN'
	WHEN t2.CountryCode = '23' THEN 'AUSTRALIA' --'AUSTRALIAN'
	WHEN t2.CountryCode = '24' THEN 'CANADA' -- 'CANADIAN'
	WHEN t2.CountryCode = '25' THEN 'SWITZERLAND' -- 'SWISS'
	WHEN t2.CountryCode = '26' THEN  'GERMANY'--'GERMAN'
	WHEN t2.CountryCode = '27' THEN 'NETHERLANDS'--'DUTCH'
	WHEN t2.CountryCode = '32' THEN 'AUSTRIA'--'AUSTRIAN'
	ELSE 'AMERICAN SAMOA'END) 
else 'Nepal' end as RESIDENCE_COUNTRY

,'' AS RESIDENCE_SINCE
,CASE WHEN MaritalStatus='N' THEN 'SNGLE' 
 WHEN MaritalStatus='S' THEN 'SNGLE' 
 WHEN MaritalStatus='D' THEN 'DVORC'  
 WHEN MaritalStatus='W' THEN 'WIDOW' 
 WHEN MaritalStatus='M' THEN 'MARRD' 
 ELSE 'MIG' END AS MARITAL_STATUS
,'' AS ANNIVERSARY_DATE
,'' AS INCOME_NATURE
,'' AS PAYMENT_MODE
,'' AS ANNUAL_RENTAL_INCOME
,'' AS ANNUAL_STOCK_BOND_INCOME
,'' AS ANNUAL_OTHERS_INCOME
,'' AS ANNUAL_TOTAL_INCOME
,'' AS REFERENCE_CURRENCY_INCOME
,'' AS BASE_CURRENCY_INCOME
,'' AS ANNUAL_OPERATING_EXP
,'' AS ANNUAL_LOAN_INSTAL
,'' AS ANNUAL_INTPROD_EXP
,'' AS ANNUAL_EXTPROD_EXP
,'' AS ANNUAL_COMMIT_EXP
,'' AS ANNUAL_OTHER_EXP
,'' AS REFERENCE_CURRENCY_EXP
,'' AS BASE_CURRENCY_EXP
,'' AS ANNUAL_TOTAL_EXP
,'977' AS HOMEPHONENOCOUNTRYCODE
,'' AS HOMEPHONENOCITYCODE
,'' AS HOMEPHONENOLOCALCODE
,'' AS WORKPHONENOCOUNTRYCODE
,'' AS WORKPHONENOCITYCODE
,'' AS WORKPHONENOLOCALCODE
,'' AS CELLPHONENOCOUNTRYCODE
,'' AS CELLPHONENOCITYCODE
,'' AS CELLPHONENOLOCALCODE
,'' AS FAXNOCOUNTRYCODE
,'' AS FAXNOCITYCODE
,'' AS FAXNOLOCALCODE
,'' AS PAGERNO
,'' AS PAGERNOCOUNTRYCODE
,'' AS PAGERNOAREACODE
,'' AS PAGERNOLOCALCODE
,'' AS SALALLOWANCES
,'' AS SALPRORATAMONTHLYINCENTIVE
,'' AS SALINTERESTSUBSIDY
,'' AS SALOTHERINCOME2
,'' AS SALOTHERINCOME3
,'' AS TOTALESTACCOUNTVALUE
,'' AS TOTALINVESTMENT
,'' AS TOTALMONTHLYDEBTSERVICEAMT
,'' AS SELFEMPTAXRETURNFIELD
,'' AS SELFEMPGROSSRECIPTCURRENTYR
,'' AS SELFEMPGROSSRECEIPTPRIORYEAR
,'' AS SELFEMPNETPROFITCURRENTYR
,'' AS SELFEMPNETPROFITPRIORYR
,'' AS SELFEMPDEPRECIATIONCURRENTYEAR
,'' AS SELFEMPDEPRECIATIONPRIORYEAR
,'' AS SELFEMPAVERAGEANNUALTURNOVER
,'' AS TOTALHOUSEHOLDINCM
,'' AS DONOTMAILFLAG
,'' AS DONOTCALLFLAG
,'' AS HOLDMAILFLAG
,'' AS HOLDMAILDESCRIPTION
,'' AS DONOTSENDEMAILFLG
,'' AS HOLDMAILSTARTDATE
,'' AS HOLDMAILENDDATE
,'' AS PREFCONTTIME
,'' AS PREFDAYTIMECONTNO
,'' AS PREFDAYTIMECONTNOLOCAL
,'' AS PREFDAYTIMECONTNOAREA
,'' AS PREFDAYTIMECONTNOCOUNTRY
,'' AS PHONEOTHER
,'' AS PHONEOTHERLOCAL
,'' AS PHONEOTHERAREA
,'' AS PHONEOTHERCOUNTRY
,'' AS CU_ANNUAL_SALARY_INCOME
,'' AS CU_ANNUAL_RENTAL_INCOME
,'' AS CU_ANNUAL_STOCK_BOND_INCOME
,'' AS CU_ANNUAL_OTHERS_INCOME
,'' AS CU_ANNUAL_TOTAL_INCOME
,'' AS CU_ANNUAL_OPERATING_EXP
,'' AS CU_ANNUAL_LOAN_INSTAL
,'' AS CU_ANNUAL_INTPROD_EXP
,'' AS CU_ANNUAL_EXTPROD_EXP
,'' AS CU_ANNUAL_COMMIT_EXP
,'' AS CU_ANNUAL_OTHER_EXP
,'' AS CU_ANNUAL_TOTAL_EXP
,'' AS CU_SALALLOWANCES
,'' AS CU_SALPRORATAMONTHLYINCENTIVE
,'' AS CU_SALINTERESTSUBSIDY
,'' AS CU_SALOTHERINCOME2
,'' AS CU_SALOTHERINCOME3
,'' AS CU_TOTALESTACCOUNTVALUE
,'' AS CU_TOTALINVESTMENT
,'' AS CU_TOTALMONTHLYDEBTSERVICEAMT
,'' AS CU_SELFEMPTAXRETURNFIELD
,'' AS CU_SELFEMPGROSSRECIPTCURRENTYR
,'' AS CU_SELFEMPGROSSRECEIPTPRIORYR
,'' AS CU_SELFEMPNETPROFITCURRENTYR
,'' AS CU_SELFEMPNETPROFITPRIORYR
,'' AS CU_SELFEMPDEPRCURRYR
,'' AS CU_SELFEMPDEPRPRIORYR
,'' AS CU_SELFEMPAVGANNUALTURNOVER
,'' AS CU_TOTALHOUSEHOLDINCM
,'' AS CU_INVESTMENTSHARESANDUNITS
,t2.Phone  AS USERFIELD1
,'' AS USERFIELD2
,'' AS USERFIELD3
,'' AS USERFLAG1
,'' AS USERFLAG2
,'' AS ALERT1
,'' AS ALERT2
,'' AS ALERT3
,'' AS ALERT4
,'' AS ALERT5
,'' AS BANK_DEFINED_DEMO_VAR1
,'' AS BANK_DEFINED_DEMO_VAR2
,'' AS BANK_DEFINED_DEMO_VAR3
,'' AS BANK_DEFINED_DEMO_VAR4
,'' AS BANK_DEFINED_DEMO_VAR5
,'' AS BANK_DEFINED_DEMO_VAR6
,'' AS BANK_DEFINED_DEMO_VAR7
,'' AS BANK_DEFINED_DEMO_VAR8
,'' AS BANK_DEFINED_DEMO_VAR9
,'' AS BANK_DEFINED_DEMO_DATE1
,'' AS BANK_DEFINED_DEMO_DATE2
,'' AS BANK_DEFINED_DEMO_DATE3
,'' AS BANK_DEFINED_DEMO_DATE4
,'' AS BANK_DEFINED_DEMO_DATE5
,'' AS BANK_DEFINED_DEMO_DATE6
,'' AS BANK_DEFINED_DEMO_DATE7
,'' AS USERFIELD4
,'' AS USERFIELD5
,'' AS USERFIELD6
,CASE WHEN MaritalStatus='M' THEN 'Married' ELSE '' END AS USERFIELD7        -- Need to be confirmed as marked in red color
,'' AS USERFIELD8
,'' AS USERFIELD9
,'' AS USERFIELD10
,'' AS AMOUNT1
,'' AS AMOUNT2
,'' AS AMOUNT3
,'' AS AMOUNT4
,'' AS AMOUNT5
,'' AS AMOUNT6
,'' AS AMOUNT7
,'' AS INTFIELD1
,'' AS INTFIELD2
,'' AS INTFIELD3
,'' AS INTFIELD4
,'' AS INTFIELD5
,'' AS TOTAL_DEDUCTIONS
,'' AS CU_TOTAL_DEDUCTIONS
,'' AS NET_SAVINGS
,'' AS CU_NET_SAVINGS
,'' AS NET_HOUSEHOLD_INCOME
,'' AS CU_NETHOUSEHOLDINCOME
,'' AS SHAREHOLDERTYPE
,'' AS SHAREHOLDEREFFECTIVEDATE
,'' AS TOTALSHARESVALUE
,'' AS CU_TOTALSHARESVALUE
,'' AS NUMBEROFSHARES
,'' AS CUSTOTHERBANKCODE
,'' AS CU_CUSTDEPOSITSINOTHERBANKS
,'' AS CU_CUSTBUSINESSASSETS
,'' AS CU_CUSTPROPERTYASSETS
,'' AS CU_CUSTINVESTMENTS
,'' AS CU_CUSTNETWORTH
,'' AS CUSTASSETSASONDATE
,'' AS CU_CUSTASSETSASONDATE
,'DEF_EMPLOYER' AS EMPLOYERSNAME    -- Need to be confirmed as marked in red
,isnull(t2.SourceofFunds, '') AS SOURCEOFINCOME  --should provide value in 2nd mock sahayogi
,'' AS CU_TOTALFUNDBASE
,'' AS CU_TOTALNONFUNDBASE
,'' AS OTHERLIMITS
,'' AS CU_OTHERLIMITS
,'' AS TDSTABLECODE
,'' AS TDSTABLE
,'' AS TDSCUSTID
,'' AS EMPLOYERID
,'' AS NRERELATIVECODE
,'' AS NRERELATIVE
,'' AS EMPLOYERID_CODE
,'' AS CHANNELSACCESSED
,'' AS OUTSTANDING_MORTAGE
,'' AS CU_OUTSTANDING_MORTGAGE
,'01' AS BANK_ID
,'' AS EMPLOYERSNAME_ALT1
,'' AS NRERELATIVENAME_ALT1
,'' AS TAX_EXMPT_START_DATE
,'TDS05' AS TAX_RATE_TABLE_CODE --BY DURGA DAI
--,(select REPLACE(REPLACE(CONVERT(VARCHAR,Today,106), ' ','-'), ',','') from ControlTable) AS NO_TAX_RECAL_BEYOND_DATE
FROM Master t1 JOIN ClientTable t2 ON t1.ClientCode = t2.ClientCode
join FINMIG..GEN_CIFID G on G.ClientCode = t1.ClientCode
WHERE G.ClientSeg = 'R'
ORDER BY ORGKEY


--346887 rows third migration 